# Generated by Django 5.1.6 on 2025-04-27 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyevent',
            name='spots',
            field=models.IntegerField(default=10),
        ),
    ]
