# Generated by Django 5.1.6 on 2025-04-28 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_studyevent_spots'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyevent',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='studyevent',
            name='spots',
            field=models.IntegerField(default=5),
        ),
    ]
