# Generated by Django 5.1.6 on 2025-04-28 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_studyevent_address_alter_studyevent_spots'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studyevent',
            name='spots',
        ),
    ]
