# Generated by Django 5.1.6 on 2025-04-28 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_studyevent_spots'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyevent',
            name='spots',
            field=models.IntegerField(default=10),
        ),
    ]
