# Generated by Django 5.1.6 on 2025-04-28 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_studyevent_spots'),
        ('home', '0005_locations_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyevent',
            name='location_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.locations'),
        ),
    ]
