# Generated by Django 5.1.5 on 2025-04-28 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_studyevent_location_object'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyevent',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
