# Generated by Django 5.2 on 2025-04-29 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_studyevent_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyevent',
            name='vibe',
            field=models.CharField(choices=[('grind', 'Grind Study'), ('quiet', 'Quiet Study'), ('casual', 'Casual Study')], default='grind', max_length=10),
        ),
    ]
