# Generated by Django 5.1.5 on 2025-04-27 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locations',
            name='spot',
        ),
        migrations.AddField(
            model_name='locations',
            name='spots',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='locations',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
