# Generated by Django 5.1.5 on 2025-04-27 02:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_locations_spot_locations_spots_locations_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 1, 12, 0)),
        ),
    ]
