# Generated by Django 5.1.5 on 2025-04-27 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_locations_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='lat',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='locations',
            name='lng',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='locations',
            name='place_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
