# Generated by Django 5.1.5 on 2025-04-27 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_locations_lat_locations_lng_locations_place_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
